theme: jekyll-theme-hacker
title: AI Customer Support
description: 📚 Curated collection of blogs and papers on how different companies are using machine learning in production for better customer support.
